### ISSUE TITLE
Too loose type checking in extractors

### ISSUE THREAD

**Issue by SimonMandlik** [CTUAvastLab/JsonGrinder.jl#76]
Currently, JsonGrinder doesn't perform any type checking in extraction:

```julia
julia> e = ExtractArray(ExtractScalar(Float32))
Array of
  └── Float32

julia> e((1,2,3))
BagNode with 1 obs
  └── ArrayNode(1×0 Array with Float32 elements) with 0 obs

julia> e(nothing)
BagNode with 1 obs
  └── ArrayNode(1×0 Array with Float32 elements) with 0 obs

julia> e(e)
BagNode with 1 obs
  └── ArrayNode(1×0 Array with Float32 elements) with 0 obs

```

This can lead to silent, hard-to-detect errors. Shouldn't we use types stored in extractor `e`, or at least check that the input is anything that can come out of `JSON.parse`?

**Comment by racinmat** [comment]
Checking the input seems like a good idea, but we should not make it too strict. 
Some of our code uses JSON3, which uses different dict-like and array-like structures, so making it too strict would make it impossible to use with other packages.
Also, we might want to support e.g. loading data from parquet and I'm not sure which types are there. 
So it's hard to figure out where to draw the line although I would really like some prevention of these bugs while maintaining the needed level of flexibility. 
Any thoughts @pevnak  @horakka5 ?

**Comment by SimonMandlik** [comment]
We can use abstract types (`AbstractVector{T}` for `ExtractVector and `AbstractDict` for `ExtractDict`). I don't know about parquet, but structures in `JSON3` are subtypes of these.

**Comment by racinmat** [comment]
I like it. I will make some simple experiments with Parquet just to make sure we don't break things, and then I would do that.
