### ISSUE TITLE
Fix bug with slicing in version 1 and examine if it's also in JsonGrinder 2

### ISSUE THREAD

**Issue by racinmat** [CTUAvastLab/JsonGrinder.jl#81]
There is a bug https://github.com/CTUAvastLab/JsonGrinder.jl/blob/ea0aeac760b13cf87b7056ef6415e14e6a04ec89/test/extractors.jl#L734-L760 in JsonGrinder 1.8.0, the slicing should work and should not raise `BoundsError`. 
Examine if it's happening also on master.

**Comment by simonmandlik** [comment]
Not an issue since https://github.com/CTUAvastLab/JsonGrinder.jl/commit/5870e239de4f61cda682c5f5da301a3064432ed2
